### PR TITLE
feat: Introduce a concept of system errors

### LINKED ISSUE #548: Provide information about system errors
This is a great question. I would suggest to generate a separate report for system errors (IO error, out of memory, exception raised in a validation etc). 

Rationale.
------------
1. Program that runs the validator needs to know why it crashed and a JSON report is more convenient than parsing stdout.
2. There may be bugs in individual validations and we need information about them.
3. We should not leak information about system errors to clients, so system errors should not be placed to the same report as validation errors.

Implementation
--------------------
We can have a special subclass of `Notice` (`SystemError`). NoticeContainer called on SystemError should keep it in a separate place.

_Originally posted by @aababilov in https://github.com/MobilityData/gtfs-validator/pull/541#discussion_r539004969_

### PR DESCRIPTION
**Pull request by aababilov**
closes #548 

The base class Notice has direct two subclasses:
* ValidationNotice - for validation errors and warnings. This is the
  parent class for the most of notices, such as DuplicatedColumnNotice,
  NumberOutOfRangeError or RouteColorContrastNotice;
* SystemError - for all notices related to retrieving and processing a
  GTFS feed, but not related to the content of the feed itself (out of
  memory, failure to download etc.).

Rationale.
* Program that runs the validator needs to know why it crashed and a JSON report is more convenient than parsing stdout.
* There may be bugs in individual validations and we need information about them.
* We should not leak information about system errors to clients, so system errors should not be placed to the same report as validation errors.

This is the report generated for IndexOutOfBoundsException introduced in #552.

```
{
    "notices": [
        {
            "code": "runtime_exception_in_validator",
            "notices": [
                {
                    "exception": "java.lang.IndexOutOfBoundsException",
                    "message": "Index 0 out of bounds for length 0",
                    "validator": "org.mobilitydata.gtfsvalidator.validator.MatchingFeedAndAgencyLangValidator"
                }
            ],
            "totalNotices": 1
        }
    ]
}
```

### CODE REVIEW

**Comment by barbeau** [comment]
@aababilov Looks like a build failures in the tests on CI:

```
/home/runner/work/gtfs-validator/gtfs-validator/main/src/test/java/org/mobilitydata/gtfsvalidator/validator/OverlappingFrequencyValidatorTest.java:35: error: incompatible types: List<ValidationNotice> cannot be converted to List<Notice>
        return noticeContainer.getValidationNotices();
...
```

**Comment by aababilov** [comment]
Yep, that was failing. I upgraded to the fresh code and fixed the tests now. Please take a look.

**Comment by aababilov** [comment]
Updated to the latest master version.

File: core/src/test/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainerTest.java [hunk 1]
```diff
@@ -75,4 +95,4 @@ public String getCode() {
             return code;
         }
     }
-}
+}
```
Comment (lionel-nj) [inline core/src/test/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainerTest.java:98]:
```suggestion
}

```

EOF blank line is standard

**Review by lionel-nj — CHANGES_REQUESTED** [review]
Thanks @aababilov a few comments inline.

**Comment by lionel-nj** [comment]
Just updated this PR with code suggestion to add system errors in the main method.

**Comment by aababilov** [comment]
> Just updated this PR with code suggestion to add system errors in the main method.

Thanks a lot! Do you mind to do that in a separate PR? That would simplify the review. This PR is a blocker for my further changes, so I am interested in merging it sooner.

File: core/src/main/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainer.java [hunk 2]
```diff
@@ -37,31 +37,46 @@
     private static final int MAX_EXPORTS_PER_NOTICE_TYPE = 100000;
     private static final Gson DEFAULT_GSON = new GsonBuilder().serializeNulls().create();
 
-    private final List<Notice> notices = new ArrayList<>();
+    private final List<ValidationNotice> validationNotices = new ArrayList<>();
+    private final List<SystemError> systemErrors = new ArrayList<>();
 
-    public void addNotice(Notice notice) {
-        notices.add(notice);
+    public void addNotice(ValidationNotice notice) {
```
[the remark this answers is not in the document]
Comment (aababilov) [reply core/src/main/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainer.java:43]: I was thinking about that. My motivation to keep the old name is that it is shorter. We call addNotice much more often than addSystemError.

**Comment by lionel-nj** [comment]
> Just updated this PR with code suggestion to add system errors in the main method.
> 

> > Thanks a lot! Do you mind to do that in a separate PR? That would simplify the review. This PR is a blocker for my further changes, so I am interested in merging it sooner.

Sure thing! Done in https://github.com/MobilityData/gtfs-validator/pull/596/commits/00eb9f6693516969864fcdf333ab299c85518829. Modifications have been relocated in #602

**Comment by aababilov** [comment]
Merci beaucoup!

File: core/src/main/java/org/mobilitydata/gtfsvalidator/notice/ValidationNotice.java [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+
+import java.util.Map;
+
+/**
+ * ValidationNotice is the base class for all validation errors and warnings
+ * related to the content of a GTFS feed.
+ * <p>
+ * This is the parent class for the most of notices, such as
+ * {@link DuplicatedColumnNotice}, {@link NumberOutOfRangeError} or notices
+ * produced by user-implemented validators.
```
Comment (barbeau) [inline core/src/main/java/org/mobilitydata/gtfsvalidator/notice/ValidationNotice.java:27]: I'm not sure "user-implemented" is clear here - maybe "3rd party" instead, if that is what is intended (i.e., validators not contained in the MobilityData repo)?

File: main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java [hunk 4]
```diff
@@ -76,7 +78,8 @@ public static void main(String[] argv) {
                 gtfsInput = GtfsInput.createFromPath(Paths.get(args.getInput()));
             }
         } catch (IOException | URISyntaxException | InterruptedException e) {
-            e.printStackTrace();
+            // FIXME: Add system errors to noticeContainer here.
```
Comment (barbeau) [inline main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java:81]: Could you open an issue pointing to this `FIXME` with more context if it's not going to be implemented in this PR?

**Review by barbeau — COMMENTED** [review]
Thanks @aababilov, this looks good. Some thoughts in-line, and conflicts from the other merged PR also need to be resolved.

File: main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java (hunk 4 above)
Comment (lionel-nj) [reply main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java:81]: It's open here: https://github.com/MobilityData/gtfs-validator/pull/602

File: core/src/main/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainer.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (lionel-nj) [reply core/src/main/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainer.java:43]: That's a good point, but I believe that since our IDEs perform autocompletion it would not add a lot of complexity.

File: main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java (hunk 4 above)
Comment (aababilov) [reply main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java:81]: Thanks!

File: core/src/main/java/org/mobilitydata/gtfsvalidator/notice/ValidationNotice.java (hunk 3 above)
Comment (aababilov) [reply core/src/main/java/org/mobilitydata/gtfsvalidator/notice/ValidationNotice.java:27]: Good point. Rephrased.

**Comment by aababilov** [comment]
Thanks for the review!

File: core/src/main/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainer.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (aababilov) [reply core/src/main/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainer.java:43]: I still would like to keep names shorter :) We already have too long names like StopTimeWithArrivalBeforePreviousDepartureTimeNotice. You may argue that there is a very small difference between the following fragments. Up to you. I can rename this method.

```
                    noticeContainer.addNotice(new StopTimeWithArrivalBeforePreviousDepartureTimeNotice(
                            stopTime.csvRowNumber(), stopTimeList.get(previousDepartureRow).csvRowNumber(), stopTime.tripId(),
                            stopTime.arrivalTime(), stopTimeList.get(previousDepartureRow).departureTime()
                    ));
```

```
                    noticeContainer.addValidationNotice(new StopTimeWithArrivalBeforePreviousDepartureTimeNotice(
                            stopTime.csvRowNumber(), stopTimeList.get(previousDepartureRow).csvRowNumber(), stopTime.tripId(),
                            stopTime.arrivalTime(), stopTimeList.get(previousDepartureRow).departureTime()
                    ));
```

**Comment by aababilov** [comment]
Note that I apply clang-format to my CLs. That saves my time because I can just run "sed" to rename a method and then format everything automatically. I propose to add my clang-format style file to the repository so that we always follow the same consistent style and never argue about new lines and spaces.

File: core/src/main/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainer.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (barbeau) [reply core/src/main/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainer.java]: I agree with keeping the name shorter. I have a tendency to be too verbose with variable and method names myself, and I've been trying to cut back 😄

**Comment by barbeau** [comment]
>Note that I apply clang-format to my CLs. That saves my time because I can just run "sed" to rename a method and then format everything automatically. I propose to add my clang-format style file to the repository so that we always follow the same consistent style and never argue about new lines and spaces.

@aababilov It's been on my TODO list to look at integrating this into the repo - https://github.com/google/google-java-format. There are a few options, either integrating into Gradle and/or via GitHub hooks. I believe this would accomplish what you're proposing?

**Review by barbeau — APPROVED** [review]
👍
